"""function_index.py - generated per-module function/class index, with a
freshness guard that fails if the committed FUNCTION_INDEX.md drifts from
the tree it describes.

Why generated, not hand-written: a hand-maintained index drifts the moment
someone adds a function and forgets to update it, and a drifted index is
worse than none, because it gets trusted. This follows the same principle
as camera_backend.py's assert_only_camera_backend_imports_sensor_profiles,
which discovers sensor-profile modules by shape rather than from a
maintained list -- derived beats maintained.

Why grouped by module, not alphabetical: an agent reading this knows the
concern (e.g. "green-plane caching"), not the identifier. An alphabetical
list across 22k lines interleaves calibrate.py and qt_shell.py with no
context; grouping by module keeps each file's surface together.

Usage:
  python3 function_index.py --write          regenerate FUNCTION_INDEX.md
  python3 function_index.py --render-check    headless self-check (also
                                               calls assert_function_index_current)

Terse by design -- this is for navigation, not documentation. One line per
top-level function or class, its signature only. "# CAVEAT:" comments are
harvested from anywhere in the file and attached to the nearest enclosing
definition, rolled up to its top-level owner: the durable fact travels
with the code, including through a future relocation, since regenerating
after a move re-derives where it now lives rather than leaving a stale
pointer.
"""
from __future__ import annotations

import ast
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
INDEX_PATH = PROJECT_ROOT / "FUNCTION_INDEX.md"

HEADER = """# Function Index

Generated by `function_index.py` -- do not hand-edit. Regenerate with
`python3 function_index.py --write` after any structural change (a
function/class added, removed, renamed, or re-signatured; a `# CAVEAT:`
comment added or removed), then commit the result. `assert_function_index_current`
(wired into `qt_shell.py --render-check`, and into this module's own)
fails loudly if this file and the tree it describes disagree.

Grouped by module, source order within a module -- not alphabetical. Look
up by concern (which file), not by a name you'd already have to know.
"""


def _signature_line(node: ast.AST) -> str:
    """Terse one-line signature for a top-level FunctionDef/AsyncFunctionDef/
    ClassDef, built by unparsing a body-stripped copy of the node -- this
    reuses Python's own unparser for correct formatting of defaults,
    annotations, */**, and keyword-only args, rather than reimplementing it."""
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        cls = ast.FunctionDef if isinstance(node, ast.FunctionDef) else ast.AsyncFunctionDef
        fake = cls(name=node.name, args=node.args, body=[ast.Pass()],
                   decorator_list=[], returns=node.returns, type_comment=None,
                   lineno=1, col_offset=0)
    elif isinstance(node, ast.ClassDef):
        fake = ast.ClassDef(name=node.name, bases=node.bases, keywords=node.keywords,
                            body=[ast.Pass()], decorator_list=[],
                            lineno=1, col_offset=0)
    else:
        raise TypeError("not a function or class node: {!r}".format(node))
    text = ast.unparse(fake)
    return text.split(":\n", 1)[0] + ":"


def _iter_defs(tree: ast.Module):
    """Yield (node, qualname, top_level_name) for every FunctionDef/
    AsyncFunctionDef/ClassDef at ANY nesting depth, in source order.
    qualname is dotted ("Picamera2Camera.__init__"); top_level_name is
    the name of the top-level def it lives under (itself, if it IS
    top-level) -- this is what a nested CAVEAT rolls up to."""
    def walk(node, stack):
        for child in ast.iter_child_nodes(node):
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                qualname = ".".join(stack + [child.name])
                top_level = stack[0] if stack else child.name
                yield child, qualname, top_level
                yield from walk(child, stack + [child.name])
            else:
                yield from walk(child, stack)
    yield from walk(tree, [])


def _harvest_caveats(src_lines: list[str]):
    """Scan raw source lines for a "# CAVEAT:" comment (comments aren't
    part of the AST, so this reads text directly, not the parse tree) and
    return a list of (start_line, end_line, text) -- text is every
    continuation comment line joined into one string, so a multi-line
    caveat block reads as one durable fact rather than being truncated at
    its first line."""
    caveats = []
    i = 0
    n = len(src_lines)
    while i < n:
        line = src_lines[i]
        stripped = line.strip()
        if stripped.startswith("# CAVEAT:") or stripped.startswith("#CAVEAT:"):
            start = i + 1   # 1-indexed, matches ast lineno
            parts = [stripped.split(":", 1)[1].strip()]
            j = i + 1
            while j < n:
                nxt = src_lines[j].strip()
                if nxt.startswith("#") and not nxt.startswith("#!"):
                    parts.append(nxt.lstrip("#").strip())
                    j += 1
                else:
                    break
            caveats.append((start, j, " ".join(p for p in parts if p)))
            i = j
        else:
            i += 1
    return caveats


def _module_entry(path: Path) -> str:
    src = path.read_text()
    src_lines = src.splitlines()
    tree = ast.parse(src, filename=str(path))

    defs = list(_iter_defs(tree))
    top_level = [(node, qualname) for node, qualname, top in defs
                 if qualname == top]   # qualname == top-level name itself

    caveats_by_top = {}
    module_level_caveats = []
    for start, end, text in _harvest_caveats(src_lines):
        owner = None
        best_span = None
        for node, qualname, top in defs:
            if node.lineno <= start <= (node.end_lineno or node.lineno):
                span = (node.end_lineno or node.lineno) - node.lineno
                if best_span is None or span < best_span:
                    best_span = span
                    owner = (qualname, top)
        if owner is None:
            module_level_caveats.append((start, text))
        else:
            qualname, top = owner
            caveats_by_top.setdefault(top, []).append((qualname, text))

    lines = ["## {}".format(path.name), ""]
    if not top_level:
        lines.append("*(no top-level functions or classes)*")
        lines.append("")
        return "\n".join(lines)

    for node, name in top_level:
        lines.append("- `{}`".format(_signature_line(node)))
        for qualname, text in caveats_by_top.get(name, []):
            where = qualname if qualname != name else name
            lines.append("  - CAVEAT (`{}`): {}".format(where, text))
    if module_level_caveats:
        lines.append("")
        lines.append("Module-level caveats (not attached to any def):")
        for start, text in module_level_caveats:
            lines.append("  - line {}: {}".format(start, text))
    lines.append("")
    return "\n".join(lines)


def build_index(root: Path = PROJECT_ROOT) -> str:
    """Deterministic: explicit sorted() on the file list (glob order is
    filesystem-dependent, not guaranteed stable across machines or runs),
    and within each module the AST body's own source order (a fresh parse
    of unchanged text always yields the same order, so nothing further
    to sort there)."""
    modules = sorted(root.glob("*.py"), key=lambda p: p.name)
    parts = [HEADER]
    for path in modules:
        parts.append(_module_entry(path))
    return "\n".join(parts).rstrip() + "\n"


def assert_function_index_current(root: Path = PROJECT_ROOT, index_path: Path = INDEX_PATH):
    """The freshness guard. Regenerates the index in memory and compares it,
    byte-for-byte, against the committed file -- fails loudly on any drift,
    naming the fix, rather than silently trusting a stale index."""
    assert index_path.exists(), (
        "{} does not exist -- run `python3 function_index.py --write` "
        "and commit the result".format(index_path.name))
    generated = build_index(root)
    committed = index_path.read_text()
    assert generated == committed, (
        "{} is stale: the tree no longer matches the committed index. "
        "Regenerate with `python3 function_index.py --write` and commit "
        "the result -- a drifted index is worse than none, because it "
        "gets trusted.".format(index_path.name))


def render_check():
    import tempfile

    # --- determinism: two independent builds of the real tree must be
    # byte-for-byte identical, not just equal in content ---------------
    first = build_index(PROJECT_ROOT)
    second = build_index(PROJECT_ROOT)
    assert first == second, "build_index() is not deterministic across two runs"
    print("determinism check PASS: two independent build_index() runs over "
          "the real tree produce byte-identical output")

    # --- signature formatting: defaults, annotations, *args/**kwargs, ---
    # --- async, and a class with bases, all in one synthetic module -----
    with tempfile.TemporaryDirectory() as td:
        tmp_root = Path(td)
        (tmp_root / "sample_module.py").write_text(
            '"""sample_module.py - synthetic fixture, not a real project module."""\n'
            "\n"
            "def plain(a, b=1, *args, c, d=2, **kwargs):\n"
            "    return a\n"
            "\n"
            "\n"
            "async def coro(x: int, y=None) -> None:\n"
            "    pass\n"
            "\n"
            "\n"
            "class Widget(Base1, Base2):\n"
            "    def __init__(self, spec):\n"
            "        # CAVEAT: spec must be pre-validated by the caller -- this\n"
            "        # constructor does not re-check it, on purpose, to avoid a\n"
            "        # second source of truth for the validation rule.\n"
            "        self.spec = spec\n"
        )
        out = build_index(tmp_root)
        assert "## sample_module.py" in out, "module header missing"
        assert "def plain(a, b=1, *args, c, d=2, **kwargs):" in out, \
            "plain function signature not rendered correctly: {!r}".format(out)
        assert "async def coro(x: int, y=None) -> None:" in out, \
            "async signature not rendered correctly"
        assert "class Widget(Base1, Base2):" in out, \
            "class signature (with bases) not rendered correctly"
        assert "CAVEAT (`Widget.__init__`):" in out, \
            "caveat inside a nested method must roll up to its top-level " \
            "class, tagged with the qualified name it actually lives at"
        assert "pre-validated by the caller" in out and "second source of truth" in out, \
            "a multi-line CAVEAT comment must be joined into one durable fact, " \
            "not truncated at its first line"
        print("signature/caveat harvesting check PASS: plain/async/class "
              "signatures render correctly, a CAVEAT nested inside a method "
              "rolls up to its top-level class tagged with the qualified "
              "name, multi-line CAVEAT text is joined rather than truncated")

    # --- every module in the real tree appears -------------------------
    out = build_index(PROJECT_ROOT)
    real_modules = sorted(p.name for p in PROJECT_ROOT.glob("*.py"))
    for name in real_modules:
        assert "## {}".format(name) in out, \
            "{} is missing from the generated index".format(name)
    print("coverage check PASS: all {} modules in the tree appear in the "
          "generated index".format(len(real_modules)))

    # --- the freshness guard itself: passes against the committed file,
    # and actually detects drift when the tree and the file disagree ----
    assert_function_index_current()
    print("assert_function_index_current check PASS: the committed "
          "FUNCTION_INDEX.md matches a fresh regeneration of the real tree")

    with tempfile.TemporaryDirectory() as td:
        tmp_root = Path(td)
        stale_index = tmp_root / "FUNCTION_INDEX.md"
        stale_index.write_text("stale content that will never match\n")
        (tmp_root / "sample_module.py").write_text("def only_fn():\n    pass\n")
        try:
            assert_function_index_current(root=tmp_root, index_path=stale_index)
            raise AssertionError("expected AssertionError for a deliberately stale index")
        except AssertionError as e:
            assert "stale" in str(e), "wrong failure reason: {}".format(e)
    print("assert_function_index_current negative check PASS: a genuinely "
          "stale index is rejected, not silently accepted")

    print("function_index self-check PASS")


if __name__ == "__main__":
    if "--write" in sys.argv:
        INDEX_PATH.write_text(build_index(PROJECT_ROOT))
        print("wrote", INDEX_PATH)
    elif "--render-check" in sys.argv:
        render_check()
    else:
        sys.exit("function_index.py: pass --write to regenerate {}, or "
                 "--render-check for the headless self-check.".format(INDEX_PATH.name))
