"""function_index.py - generates FUNCTION_INDEX.md, a per-module index of
every top-level function and class, grouped by module rather than
flattened alphabetically, with terse signatures for navigation, not
documentation.

Why generated rather than hand-maintained: a hand-edited index drifts the
first time someone adds a function and forgets it, and a drifted index is
worse than none, because it gets trusted. Same reasoning
camera_backend.py's assert_only_camera_backend_imports_sensor_profiles
already applies to sensor-profile discovery -- derived beats maintained.

The generator has two independent halves. The signature half is
structural: it walks the AST and reads only FunctionDef/AsyncFunctionDef/
ClassDef nodes directly under Module.body (not nested defs). The caveat
half is necessarily textual: Python's AST discards comments, so
"# CAVEAT:" markers are found by scanning raw source lines, then attached
to whichever top-level node's [lineno, end_lineno] range contains the
comment's line, or to a module-level bucket if none does.

Usage: `python3 function_index.py` regenerates FUNCTION_INDEX.md in place.
`python3 function_index.py --render-check` runs the self-check, including
assert_function_index_current() -- the freshness guard that fails when the
committed file and a fresh regeneration disagree. See CHANGELOG.md's
"generated per-module function index" entries for why it's built this way
and where the guard is wired in.
"""
from __future__ import annotations

import ast
import copy
import difflib
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
OUTPUT_PATH = REPO_ROOT / "FUNCTION_INDEX.md"

# A caveat line starts a block; a continuation line is any comment line at
# the same indentation immediately following it that does NOT itself start
# a new caveat (so two adjacent "# CAVEAT:" comments never merge into one).
_CAVEAT_START_RE = re.compile(r"^(\s*)#\s*CAVEAT:\s*(.*)$")
_COMMENT_LINE_RE = re.compile(r"^(\s*)#\s?(.*)$")

_HEADER = """\
# Function Index

Generated by `function_index.py` -- do not hand-edit. Regenerate with
`python3 function_index.py` after changing a module's top-level functions
or classes, or its `# CAVEAT:` comments, then commit the result.
`assert_function_index_current` (run via `python3 function_index.py
--render-check`) fails the moment this file and a fresh regeneration
disagree, so a stale index is a build failure, not a silent drift.

Grouped by module -- an agent greps blind for a *concern*, not an
*identifier*, so a flat alphabetical list across ~22k lines would give
back names with no surrounding context. Signatures are terse (one line,
via `ast.unparse`); `# CAVEAT:` blocks below a signature are the durable
facts worth reading in full.
"""


def _discover_modules(root: Path) -> list[Path]:
    """All *.py files directly in root, sorted by filename.

    Explicit sort, never Path.glob's own order: glob order follows
    directory-entry order, which is filesystem-dependent and not something
    to build a freshness guard on top of.

    # CAVEAT: never iterate a bare set() of strings straight into this
    # generator's output. CPython randomizes string hash seeds per
    # process by default, so a set's iteration order is stable WITHIN one
    # run but not guaranteed to match a second process's run -- it would
    # pass a same-process determinism check and then flap between
    # unrelated `python3 function_index.py` invocations, which is exactly
    # the kind of spurious failure that gets a guard disabled. Sort
    # explicitly wherever order is observable in the output.
    """
    return sorted(root.glob("*.py"), key=lambda p: p.name)


def _top_level_nodes(tree: ast.Module) -> list[ast.AST]:
    return [
        node for node in tree.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
    ]


def _signature_lines(node: ast.AST) -> list[str]:
    """Terse single-definition signature: decorators (if any) plus the
    def/class header line, no body.

    # CAVEAT: this shallow-copies the node and REPLACES clone.body with a
    # fresh list rather than mutating node.body in place. top_level_nodes
    # holds live references to the same nodes reused later for caveat
    # line-range bucketing; mutating a node's body here would corrupt that
    # bucketing (end_lineno is computed from the ORIGINAL body's extent).
    """
    clone = copy.copy(node)
    clone.body = [ast.Pass()]
    lines = ast.unparse(clone).splitlines()
    return lines[:-1]  # drop the synthetic "    pass" line


def _harvest_caveats(lines: list[str]) -> list[tuple[int, str]]:
    """Returns (1-indexed start line, merged text) for every "# CAVEAT:"
    block: the marker line plus any immediately-following same-indent
    comment-only lines.

    # CAVEAT: this file's own comments must never start a physical line
    # with "# CAVEAT:" when merely describing the marker in prose (as this
    # docstring block does, by writing it mid-line) -- the harvester
    # matches raw text, so a literal example at the start of a line would
    # be indexed as a real caveat attached to whatever definition follows.
    """
    out: list[tuple[int, str]] = []
    i, n = 0, len(lines)
    while i < n:
        start_match = _CAVEAT_START_RE.match(lines[i])
        if not start_match:
            i += 1
            continue
        indent, first = start_match.group(1), start_match.group(2).strip()
        parts = [p for p in [first] if p]
        j = i + 1
        while j < n:
            cont_match = _COMMENT_LINE_RE.match(lines[j])
            if not cont_match or cont_match.group(1) != indent or _CAVEAT_START_RE.match(lines[j]):
                break
            text = cont_match.group(2).strip()
            if text:
                parts.append(text)
            j += 1
        out.append((i + 1, " ".join(parts)))
        i = j
    return out


def _owner_for_line(top_nodes: list[ast.AST], line: int) -> ast.AST | None:
    # CAVEAT: for a decorated def/class, node.lineno is the "def"/"class"
    # line itself, NOT the first decorator line above it -- ast puts
    # decorator_list on the node but excludes those lines from its own
    # lineno/end_lineno range. A "# CAVEAT:" comment placed above the
    # decorator(s) falls outside every top-level node's range and lands in
    # the module-level bucket instead of attaching to the decorated def.
    # Put caveat comments after the decorator line(s), immediately above
    # "def"/"class", or inside the body, not above the decorator.
    for node in top_nodes:
        end = node.end_lineno if node.end_lineno is not None else node.lineno
        if node.lineno <= line <= end:
            return node
    return None


def _render_module(path: Path) -> str:
    source = path.read_text()
    lines = source.splitlines()
    tree = ast.parse(source, filename=str(path))
    top_nodes = _top_level_nodes(tree)

    module_level: list[str] = []
    by_owner_lineno: dict[int, list[str]] = {}
    for line, text in _harvest_caveats(lines):
        owner = _owner_for_line(top_nodes, line)
        if owner is None:
            module_level.append(text)
        else:
            by_owner_lineno.setdefault(owner.lineno, []).append(text)

    out = [f"## {path.name}", ""]
    for text in module_level:
        out.append(f"> CAVEAT: {text}")
    if module_level:
        out.append("")

    if not top_nodes:
        out.append("_(no top-level functions or classes)_")
    for node in top_nodes:
        sig_lines = _signature_lines(node)
        for i, sig_line in enumerate(sig_lines):
            out.append(("- `" if i == 0 else "  `") + sig_line + "`")
        for text in by_owner_lineno.get(node.lineno, []):
            out.append(f"  > CAVEAT: {text}")
    out.append("")
    return "\n".join(out)


def generate_index_text() -> str:
    modules = _discover_modules(REPO_ROOT)
    sections = [_render_module(path) for path in modules]
    return _HEADER + "\n" + "\n".join(sections).rstrip("\n") + "\n"


def assert_function_index_current() -> None:
    """Freshness guard: regenerate in memory and compare against the
    committed FUNCTION_INDEX.md. Fails loudly on any difference, including
    the file not existing yet.
    """
    generated = generate_index_text()
    on_disk = OUTPUT_PATH.read_text() if OUTPUT_PATH.exists() else ""
    if generated == on_disk:
        return
    diff = "\n".join(difflib.unified_diff(
        on_disk.splitlines(), generated.splitlines(),
        fromfile="committed FUNCTION_INDEX.md", tofile="fresh regeneration",
        lineterm="",
    ))
    raise AssertionError(
        "FUNCTION_INDEX.md is stale -- run `python3 function_index.py` and "
        "commit the result. Diff (committed vs fresh):\n" + diff[:4000]
    )


def main() -> None:
    text = generate_index_text()
    OUTPUT_PATH.write_text(text)
    print(f"wrote {OUTPUT_PATH.name} ({len(text.splitlines())} lines, "
          f"{len(_discover_modules(REPO_ROOT))} modules)")


def render_check() -> None:
    modules = _discover_modules(REPO_ROOT)
    assert modules, "no .py modules found under REPO_ROOT -- resolved wrong?"
    assert modules == sorted(modules, key=lambda p: p.name), \
        "_discover_modules must return a filename-sorted list"
    print(f"module discovery check PASS: {len(modules)} modules, "
          f"sorted by filename ({modules[0].name} .. {modules[-1].name})")

    # Determinism, within-process: two independent generations of an
    # unchanged tree must be byte-identical. (The stronger cross-process
    # test -- two separate `python3 function_index.py` invocations, each
    # with its own PYTHONHASHSEED, diffed on disk -- is run separately;
    # see the build record in CHANGELOG.md.)
    first = generate_index_text()
    second = generate_index_text()
    assert first == second, "generator is non-deterministic within one process"
    print("determinism check PASS (within-process): two generations of an "
          "unchanged tree produced byte-identical output")

    for path in modules:
        heading = f"## {path.name}"
        assert heading in first, f"{path.name} is missing its own heading"
    print(f"module coverage check PASS: all {len(modules)} modules appear "
          f"as their own heading")

    caveat_text = (REPO_ROOT / "camera_backend.py").read_text()
    caveats = _harvest_caveats(caveat_text.splitlines())
    assert any("QGl6Picamera2" in text for _, text in caveats), \
        "camera_backend.py's binding-fix CAVEAT was not harvested"
    assert any(len(text) > 120 for _, text in caveats), \
        "a multi-line CAVEAT block must merge into one entry, not just its first line"
    print("caveat harvesting check PASS: camera_backend.py's binding-fix "
          "CAVEAT found and merged across its continuation lines")

    # Nested defs must not leak into the index: assert on a synthetic
    # example rather than this file, so the check doesn't depend on
    # function_index.py's own shape staying the same.
    sample = ast.parse(
        "def outer():\n"
        "    def inner():\n"
        "        pass\n"
        "    return inner\n"
    )
    top = _top_level_nodes(sample)
    assert len(top) == 1 and top[0].name == "outer", \
        "a nested def must not be treated as a top-level node"
    print("nested-def exclusion check PASS: only Module.body-direct defs "
          "are indexed")

    assert_function_index_current()
    print("assert_function_index_current PASS: committed FUNCTION_INDEX.md "
          "matches a fresh regeneration")

    print("function_index self-check PASS")


if __name__ == "__main__":
    if "--render-check" in sys.argv:
        render_check()
    else:
        main()
